version: '3'
services:
  app:
    image: node:lts
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8090:8000"
    command: npm run dev
    depends_on:
      - db
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
    expose:
      - 3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080